/**
 * Vendor the three typefaces (spec §10) into `public/fonts/`.
 *
 * They are self-hosted rather than linked from Google Fonts because the app is
 * meant to work offline — a font that only arrives over the network is a font
 * that vanishes in a field with no signal, which is precisely where this app is
 * used. All three are SIL Open Font License 1.1, which permits redistribution;
 * the notice is recorded in ATTRIBUTION.md.
 *
 * Run with `npm run build:fonts`. Output is committed.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { family: 'Cormorant Garamond', axis: 'wght@400;600', slug: 'cormorant-garamond' },
  { family: 'Spectral', axis: 'wght@300;400;600', slug: 'spectral' },
  { family: 'IBM Plex Mono', axis: 'wght@400;500', slug: 'ibm-plex-mono' },
];

/** Only the Latin blocks; the app has no non-Latin copy. */
const WANTED_SUBSETS = ['U+0000-00FF', 'U+0100-02BA'];

const OUT_DIR = join(process.cwd(), 'public', 'fonts');

interface FontFace {
  family: string;
  weight: string;
  style: string;
  url: string;
  unicodeRange: string;
}

function parseFaces(css: string): FontFace[] {
  const faces: FontFace[] = [];
  for (const block of css.split('@font-face').slice(1)) {
    const grab = (key: string) => new RegExp(`${key}:\\s*([^;]+);`).exec(block)?.[1]?.trim() ?? '';
    const url = /url\((https:\/\/[^)]+)\)/.exec(block)?.[1];
    if (!url) continue;
    faces.push({
      family: grab('font-family').replace(/['"]/g, ''),
      weight: grab('font-weight'),
      style: grab('font-style'),
      url,
      unicodeRange: grab('unicode-range'),
    });
  }
  return faces;
}

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });
  const rules: string[] = [
    '/* Generated by scripts/fetch-fonts.ts — do not edit by hand. */',
    '/* Cormorant Garamond, Spectral, IBM Plex Mono: SIL Open Font License 1.1. */',
    '',
  ];

  for (const { family, axis, slug } of FAMILIES) {
    const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, '+')}:${axis}&display=swap`;
    const css = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => r.text());

    const faces = parseFaces(css).filter((f) =>
      WANTED_SUBSETS.some((range) => f.unicodeRange.includes(range)),
    );

    // Google serves one face per (weight, subset). Keep the widest Latin block
    // available for each weight, which is latin-ext where it exists.
    const byWeight = new Map<string, FontFace>();
    for (const f of faces) {
      const existing = byWeight.get(f.weight);
      if (!existing || f.unicodeRange.length > existing.unicodeRange.length) byWeight.set(f.weight, f);
    }

    for (const face of byWeight.values()) {
      const name = `${slug}-${face.weight}.woff2`;
      const bytes = Buffer.from(await fetch(face.url).then((r) => r.arrayBuffer()));
      await writeFile(join(OUT_DIR, name), bytes);
      console.log(`  ${name} — ${(bytes.byteLength / 1024).toFixed(1)} kB`);

      rules.push(
        `@font-face {`,
        `  font-family: '${face.family}';`,
        `  font-style: ${face.style};`,
        `  font-weight: ${face.weight};`,
        `  font-display: swap;`,
        `  src: url('/fonts/${name}') format('woff2');`,
        `  unicode-range: ${face.unicodeRange};`,
        `}`,
        '',
      );
    }
  }

  await writeFile(join(OUT_DIR, 'fonts.css'), rules.join('\n'));
  console.log(`\nwrote public/fonts/fonts.css`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
